### ISSUE TITLE
Zaprojektować wstępnie interfejs gry

### ISSUE THREAD

**Issue by BartekLach** [BartekLach/Talia-Zwyciestwa#1]
Wygląd głównego menu, mapy (po której się poruszamy), ekwipunku (razem z handlem) oraz ekranu podczas pojedynku karcianego z przeciwnikiem.

**Comment by BartekLach** [comment]
Concept menu głównego gry
![menu](https://user-images.githubusercontent.com/31034100/77109075-984ffd00-6a23-11ea-8341-0ae21245034a.png)

**Comment by BartekLach** [comment]
Concept mapy świata 
Startujemy od dużej czarnej kropki i dalej poruszamy się wybierając punkty, do których chcemy dojść.
1. Skrzyżowane miecze - walka z przeciwnikiem (pojedynek karciany)
2. Mieszek - kupiec, u którego możemy kupić nowe karty i inne przedmioty (do ustalenia)
3. Znak zapytania - losowe miejsce (walka, wydarzenie fabularne lub kupiec)
![mapa](https://user-images.githubusercontent.com/31034100/77113011-51193a80-6a2a-11ea-84a8-708e11856f9c.png)

**Comment by szym-sicinski** [comment]
Formularze pozostałe do zrobienia jak najszybciej: Walka, Kupiec, Nagroda
